name: RealisticWeather
version: '${version}'
main: me.shradinx.realisticweather.RealisticWeather
api-version: '1.20'
commands:
  realisticweather:
    description: Main command
    aliases:
      - rw
      - rweather
    permission: realisticweather.command.default
    permission-message: You do not have permission to use this command.
  togglerw:
    description: Toggle realistic weather command
    aliases:
      - togglerealisticweather
    permission: realisticweather.admin.toggle
    permission-message: You do not have permission to use this command.
permissions:
  realisticweather.command:
    description: Allows you to use RealisticWeather commands
    default: true
    children:
      realisticweather.command.default: true
      realisticweather.command.getanemometer: true
  realisticweather.admin:
    description: Allows you to use admin commands
    default: op
    children:
      realisticweather.admin.reload: true
      realisticweather.admin.toggle: true
      realisticweather.admin.tornado: true
      realisticweather.admin.resetgravity: true
